### ISSUE TITLE
Row.getBigDecimal() and getLocalTime() on MySQL

### ISSUE THREAD

**Issue by gavinking** [smallrye/smallrye-reactive-utils#105]
The `MySQLRowImpl` doesn't support `getBigDecimal()` (the natural Java mapping for SQL `DECIMAL` or `NUMERIC`) nor `getLocalTime()` (the natural mapping for `TIME`).

**Comment by cescoffier** [comment]
This issue should be reported in https://github.com/vert-x3/vertx-mysql-postgresql-client.

**Comment by cescoffier** [comment]
See https://github.com/vert-x3/vertx-mysql-postgresql-client/issues/169.

**Comment by gavinking** [comment]
OK.

**Comment by BillyYccc** [comment]
Hi @cescoffier, I think you opened the issue in the wrong repository, it should be located in https://github.com/eclipse-vertx/vertx-sql-client instead.

I have created a ticket for this in https://github.com/eclipse-vertx/vertx-sql-client/issues/507
