### ISSUE TITLE
PostgreSQL client should recognize ? placemarkers

### ISSUE THREAD

**Issue by gavinking** [smallrye/smallrye-reactive-utils#106]
Postgres' `$1`, `$2`, etc, is nonstandard, AFAIK, and contrary to ODBC and JDBC.

We should at least have the option to use this syntax if we want to.

**Comment by cescoffier** [comment]
This issue should be reported in https://github.com/vert-x3/vertx-mysql-postgresql-client.

**Comment by cescoffier** [comment]
See https://github.com/vert-x3/vertx-mysql-postgresql-client/issues/170.

**Comment by BillyYccc** [comment]
check https://github.com/eclipse-vertx/vertx-sql-client/issues/509 instead.
