### ISSUE TITLE
No Batch Method in Pool Class?

### ISSUE THREAD

**Issue by obbyK** [smallrye/smallrye-reactive-utils#156]
I have using `quarkus-reactive-mysql-client` with mutiny api but it seems `MYSQLPool` does not have the `preparedBatch` method. Is this going to be added?

**Comment by cescoffier** [comment]
@tsegismont do you know why the method would be missing?

**Comment by cescoffier** [comment]
Actually, I can't find it at https://vertx.io/docs/apidocs/io/vertx/mysqlclient/MySQLPool.html. Where did you see this method @obbyK?

**Comment by obbyK** [comment]
I mean in `vertx-mysql-client` there is a `preparedBatch` method, so I was thinking this would be available in mutiny as well. Or was my assumption wrong?

**Comment by cescoffier** [comment]
Is `preparedBatch` method a Vert.x 4.x only method? @tsegismont do you know? 

The Mutiny classes are based on Vert.x 3.9.x.

**Comment by obbyK** [comment]
Oops. The project I was porting to quarkus was using vertx 3.8.5. The method was `preparedBatch`, but I just read the docs for 3.9.x and it was updated to `preparedQuery(String).executeBatch(Tuple) or preparedQuery(String).execute(Tuple)`. And those are available in mutiny.

**Comment by cescoffier** [comment]
Thanks for the feedback!
