### ISSUE TITLE
Logic bug in WriteStreamSubscriberImpl skipping onNext when NOT done.

### ISSUE THREAD

**Issue by syndic8-stephen** [smallrye/smallrye-reactive-utils#158]
In trying to use WriteStreamSubscriber I found my items were not being delivered.  On debug they were being skipped in onNext with "if (!done.get()) return"  It seems this is the wrong way around and we want to skip and return immediately if done is true.  I will add a pull request.

**Comment by jponge** [comment]
Fixed by #159

**Comment by jponge** [comment]
@cescoffier you can close it :-) (I don't have permissions)
