### ISSUE TITLE
[converters] rxjava1.ObservableConverter#emitAtMostOneItem returns true

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-reactive-utils#201]
I'm reviewing the converters for the purpose of supporting more async types in SmallRye Fault Tolerance and I just found this: https://github.com/smallrye/smallrye-reactive-utils/blob/1.2.2/reactive-converters/converter-rxjava1/src/main/java/io/smallrye/reactive/converters/rxjava1/ObservableConverter.java#L108

My understanding is that `Observable`, in all RxJava versions, is a stream, not a future. Hence `emitAtMostOneItem` should return `false`, but it returns `true`. This is correct in the `rxjava2` and `rxjava3` modules.

Is this just an oversight, or intentional? If a mistake, I'd be happy to submit a PR, just wanted to confirm I'm not missing something.

**Comment by cescoffier** [comment]
It's a bug - clearly.
