### ISSUE TITLE
Vert.x JUnit5 support for the Mutiny bindings

### ISSUE THREAD

**Issue by eminbahadir** [smallrye/smallrye-reactive-utils#325]

**Comment by cescoffier** [comment]
What do you have in mind? 
Our testing utilities work with junit 5.

**Comment by eminbahadir** [comment]
does vert.x mutiny work with JUnit5 or do you mean Quarkus? I created that after the conversation with @jponge.

**Comment by cescoffier** [comment]
I don't see why it would not work with junit 5. I'm using junit 5 everyday without any trouble.

This repository still uses junit 4 because the codegen TCK uses junit 4 (and mixing them is complicated).

**Comment by jponge** [comment]
@cescoffier This is about the `Vertx` context binding injection in the JUnit 5 module, there's a SPI I had designed for that and which is used by `vertx-rx`.

**Comment by jponge** [comment]
I asked @eminbahadir to create an issue from a message on `vertx-users`)

**Comment by cescoffier** [comment]
Ok, the title needs to be updated.

**Comment by jponge** [comment]
@eminbahadir see #329

**Comment by eminbahadir** [comment]
@jponge thank you
